version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name : docker-buildx
          command: |
            docker buildx create --name multiarch --use --bootstrap
      - run:
          name : build-alpine-image
          command: |
            for version in $(cat .versions); do
                docker buildx build --platform linux/arm64,linux/amd64 --build-arg node_version=${version} \
                --tag quay.io/wealthwizards/ww-base-node:alpine-${version} \
                alpine
            done
      - run:
          name : build-debian-image
          command: |
            for version in $(cat .versions); do
                docker buildx build --platform linux/arm64,linux/amd64 --build-arg node_version=${version} \
                --tag quay.io/wealthwizards/ww-base-node:debian-${version} \
                debian
            done
      - run:
          name : build-alpine-dev-image
          command: |
            for version in $(cat .versions); do
                docker buildx build --platform linux/arm64,linux/amd64 --build-arg node_version=${version} \
                --tag quay.io/wealthwizards/ww-base-node:alpine-dev-${version} \
                alpine-dev
            done
      - run:
          name : build-debian-dev-image
          command: |
            for version in $(cat .versions); do
                docker buildx build --platform linux/arm64,linux/amd64 --build-arg node_version=${version} \
                --tag quay.io/wealthwizards/ww-base-node:debian-dev-${version} \
                debian-dev
            done
      - run:
          name : build-cypress-image
          command: |
            for version in $(cat .versions-cypress); do
                docker build --build-arg cypress_version=${version} -t quay.io/wealthwizards/ww-base-node:cypress-${version} cypress
            done
      - run:
          name : build-playwright-image
          command: |
            for version in $(cat .versions-playwright); do
                docker build --build-arg playwright_version=${version} -t quay.io/wealthwizards/ww-base-node:playwright-${version} playwright
            done
  buildAndDeploy:
    machine: true
    steps:
      - checkout
      - deploy:
          name : docker-buildx-login
          command: |
            docker buildx create --name multiarch --use --bootstrap
            docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
      - deploy:
          name : build-push-alpine-image
          command: |
            for version in $(cat .versions); do
                a=( ${version//./ } )
                major_version=${a[0]}
                minor_version=${a[1]}
                docker buildx build --push --platform linux/arm64,linux/amd64 --build-arg node_version=${version} --tag quay.io/wealthwizards/ww-base-node:alpine-${version} --tag quay.io/wealthwizards/ww-base-node:alpine-${major_version}.${minor_version} --tag quay.io/wealthwizards/ww-base-node:alpine-${major_version} --tag quay.io/wealthwizards/ww-base-node:alpine-latest alpine
            done
      - deploy:
          name : build-push-debian-image
          command: |
            for version in $(cat .versions); do
                a=( ${version//./ } )
                major_version=${a[0]}
                minor_version=${a[1]}
                docker buildx build --push --platform linux/arm64,linux/amd64 --build-arg node_version=${version} --tag quay.io/wealthwizards/ww-base-node:debian-${version} --tag quay.io/wealthwizards/ww-base-node:debian-${major_version}.${minor_version} --tag quay.io/wealthwizards/ww-base-node:debian-${major_version} --tag quay.io/wealthwizards/ww-base-node:debian-latest debian
            done
      - deploy:
          name : build-push-alpine-dev-image
          command: |
            for version in $(cat .versions); do
                a=( ${version//./ } )
                major_version=${a[0]}
                minor_version=${a[1]}
                docker buildx build --push --platform linux/arm64,linux/amd64 --build-arg node_version=${version} --tag quay.io/wealthwizards/ww-base-node:alpine-dev-${version} --tag quay.io/wealthwizards/ww-base-node:alpine-dev-${major_version}.${minor_version} --tag quay.io/wealthwizards/ww-base-node:alpine-dev-${major_version} --tag quay.io/wealthwizards/ww-base-node:alpine-dev-latest alpine-dev
            done
      - deploy:
          name : build-push-debian-dev-image
          command: |
            for version in $(cat .versions); do
                a=( ${version//./ } )
                major_version=${a[0]}
                minor_version=${a[1]}
                docker buildx build --push --platform linux/arm64,linux/amd64 --build-arg node_version=${version} --tag quay.io/wealthwizards/ww-base-node:debian-dev-${version} --tag quay.io/wealthwizards/ww-base-node:debian-dev-${major_version}.${minor_version} --tag quay.io/wealthwizards/ww-base-node:debian-dev-${major_version} --tag quay.io/wealthwizards/ww-base-node:debian-dev-latest debian-dev
            done
      - deploy:
          name : build-push-cypress-image
          command: |
            for version in $(cat .versions-cypress); do
                docker build --build-arg cypress_version=${version} -t quay.io/wealthwizards/ww-base-node:cypress-${version} cypress
                docker tag quay.io/wealthwizards/ww-base-node:cypress-${version} quay.io/wealthwizards/ww-base-node:cypress-${version}
                docker tag quay.io/wealthwizards/ww-base-node:cypress-${version} quay.io/wealthwizards/ww-base-node:cypress-latest
                docker push quay.io/wealthwizards/ww-base-node:cypress-${version}
                docker push quay.io/wealthwizards/ww-base-node:cypress-latest
            done
      - deploy:
          name : build-push-playwright-image
          command: |
            for version in $(cat .versions-playwright); do
                docker build --build-arg playwright_version=${version} -t quay.io/wealthwizards/ww-base-node:playwright-${version} playwright
                docker tag quay.io/wealthwizards/ww-base-node:playwright-${version} quay.io/wealthwizards/ww-base-node:playwright-${version}
                docker tag quay.io/wealthwizards/ww-base-node:playwright-${version} quay.io/wealthwizards/ww-base-node:playwright-latest
                docker push quay.io/wealthwizards/ww-base-node:playwright-${version}
                docker push quay.io/wealthwizards/ww-base-node:playwright-latest
            done
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - buildAndDeploy:
          filters:
            branches:
              only: master
      - build:
          filters:
            branches:
              ignore: master